new: implement an async thread for generating diffs
FedeDP/troublescope pull request #13
Opened 2024-12-10 18:07 UTC by Andreagit97

2024-12-10 19:50 UTC, irozzo-1A approved these changes
LGTM just a nit

2024-12-10 19:50 UTC, irozzo-1A commented on src/async.cpp
> +		});
nit: you could avoid using an atomic by doing the following
```suggestion
        bool done = false;
	while(done) {
		// -1 should be a valid tid for async events
		generate_async_event(h, ASYNC_EVENT_DIFF_NAME, -1, "root");
		std::unique_lock<std::mutex> l(m_diff_mu);
		done = m_diff_cv.wait_for(l, std::chrono::seconds(DIFF_NOTIFY_INTERVALS), [this] {
			return m_diff_notify_thread_quit;
		});
```

2024-12-10 20:09 UTC, FedeDP commented
My idea was to use a timerfd in the same poll async thread we already have.
Also in m_cfg we already have a userspecified timeout in seconds exactly for this event.

2024-12-10 20:09 UTC, FedeDP commented
My idea was to use a timerfd in the same poll async thread we already have.
Also in m_cfg we already have a underspecified timeout in seconds exactly for this event.

I've: I'd avoid using another thread while we can just reuse the same one we already have.

2024-12-11 07:43 UTC, FedeDP requested changes
My take: https://github.com/FedeDP/troublescope/pull/16

2024-12-11 07:54 UTC, closed without merging